name: secure_chat_client
description: Secure Chat Flutter Client with E2E encryption and WebSocket
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sodium: ^0.3.6
  http: ^0.13.4
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
